#!/bin/bash

# configure git
echo "configure git variables user.name and user.email"

git config --global user.email 26223147+suikan4github@users.noreply.github.com
git config --global user.name Suikan
git config --global push.default simple
